# Generated by Django 4.1 on 2022-10-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_book', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='user',
        ),
    ]
